[profile.release]
debug = true

[workspace]
members = [
    "processor",
    "server",
]
resolver = "2"

[workspace.dependencies]
anyhow = {version = "1.0.58", features = ["backtrace"]}
flate2 = "1.0.24"
serde = { version = "1.0.158", features = ["derive"] }
serde_json = "1.0.94"
